### ISSUE TITLE
Trouver les disponibilités communes

### ISSUE THREAD

**Issue by azomwastaken** [Guibi1/H23-Gr3-Equipe3-Univox#28]
Créer un algorithme pour trouvé les disponibilités entre une liste d'horaire. L'algorithme prend en input une liste d'horaire et return 1 object horaire des disponibilités.

Il doit y avoir des paramètres. Par exemple, si les fins/début de journée compte dans le calcul, si la fin de semaine compte...

**Comment by Guibi1** [comment]
C'est sensé servir à quoi exactement?

**Comment by azomwastaken** [comment]
> C'est sensé servir à quoi exactement?

bruh let me do it you'll understand
